config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'restaurants#index'

  #roots "pages#home"
  resources :restaurants do 
    resources :reservations, only: [:create]
  end

  resources :reserves 
  resources :reservations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reserve.rb
class Reserve < ApplicationRecord
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  before_action :set_reserf, only: [:show, :edit, :update, :destroy]

  # GET /reserves
  # GET /reserves.json
  def index
    @reserves = Reserve.all
  end

  # GET /reserves/1
  # GET /reserves/1.json
  def show
  end

  # GET /reserves/new
  def new
    @reserf = Reserve.new
  end

  # GET /reserves/1/edit
  def edit
  end

  # POST /reserves
  # POST /reserves.json
  def create
    @reserf = Reserve.new(reserf_params)

    respond_to do |format|
      if @reserf.save
        format.html { redirect_to @reserf, notice: 'Reserve was successfully created.' }
        format.json { render :show, status: :created, location: @reserf }
      else
        format.html { render :new }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reserves/1
  # PATCH/PUT /reserves/1.json
  def update
    respond_to do |format|
      if @reserf.update(reserf_params)
        format.html { redirect_to @reserf, notice: 'Reserve was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserf }
      else
        format.html { render :edit }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reserves/1
  # DELETE /reserves/1.json
  def destroy
    @reserf.destroy
    respond_to do |format|
      format.html { redirect_to reserves_url, notice: 'Reserve was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserf
      @reserf = Reserve.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserf_params
      params.require(:reserf).permit(:email, :date, :time)
    end
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/reserves/_form.html.erb
<%= form_for(reserf) do |f| %>
  <% if reserf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reserf.errors.count, "error") %> prohibited this reserf from being saved:</h2>

      <ul>
      <% reserf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.time_select :time %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reserves/edit.html.erb
<h1>Editing Reserf</h1>

<%= render 'form', reserf: @reserf %>

<%= link_to 'Show', @reserf %> |
<%= link_to 'Back', reserves_path %>

app/views/reserves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reserves</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Date</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reserves.each do |reserf| %>
      <tr>
        <td><%= reserf.email %></td>
        <td><%= reserf.date %></td>
        <td><%= reserf.time %></td>
        <td><%= link_to 'Show', reserf %></td>
        <td><%= link_to 'Edit', edit_reserf_path(reserf) %></td>
        <td><%= link_to 'Destroy', reserf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reserf', new_reserf_path %>

app/views/reserves/new.html.erb
<h1>New Reserf</h1>

<%= render 'form', reserf: @reserf %>

<%= link_to 'Back', reserves_path %>

app/views/reserves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @reserf.email %>
</p>

<p>
  <strong>Date:</strong>
  <%= @reserf.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @reserf.time %>
</p>

<%= link_to 'Edit', edit_reserf_path(@reserf) %> |
<%= link_to 'Back', reserves_path %>