config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'restaurants#index'

  #roots "pages#home"
  resources :restaurants do 
    resources :reservations, only: [:create]
  end

  resources :reserves 
  resources :reservations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :restaurant, :foreign_key => 'restaurant_id'
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  # before_action :set_restaurant
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  def show
  end

  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  
  #to create the reservation using the restaurant resource(via restaurant path), I followed http://stackoverflow.com/questions/32944854/associating-2-models-correctly-to-another-model-in-the-create-action-of-controll
  #I needed to update the form to include the restaurant and also set_restaurant id 

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = @restaurant.reservation.new(reservation_params)
    # @reservation.restaurant_id = @restaurant.id

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @restaurant, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }

        # to send out confirmation email after the reservation is made
        ReservationMailer.reservation_confirmation(@reservation, @restaurant).deliver
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # def set_restaurant
    #   @restaurant = Restaurant.find(params[:restaurant_id])
    # end  

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:email, :date_time, :message)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for [@restaurant, @reservation] do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Email %>
    <%= f.text_field :email %>
  </div>

  <div class="form-group">
    <%= f.label :Date_Time %>
    <%= f.datetime_local_field :date_time %>
  </div>

  <div class='form-group'>
    <%= f.label :Message %>
    <%= f.text_area :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <%= reservation.email %>
        <%= reservation.date_time %>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @reservation.email %> 
</p>
<p>
  <strong>Date and Time</strong>
  <%= @reservation.date_time %>
</p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>