config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'restaurants#index'

  #roots "pages#home"
  resources :restaurants do 
    resources :reservations, only: [:create]
  end

  resources :reserves 
  resources :reservations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  mount_uploader :image, RestaurantImageUploader
  belongs_to :user

  has_many :reservation
  accepts_nested_attributes_for :reservation

  validates :name, presence: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :user_signed_in?, only: [:new, :create]
  before_action :current_user, only: [:edit, :update, :destroy]
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]


  #Required for Carrierwave and mini_magick
  require 'carrierwave/orm/activerecord'

  # GET /restaurants
  # GET /restaurants.json
  # to be able to perform the actions of reservations MVC in restaurant for using the form partial in restaurant show http://stackoverflow.com/questions/26159190/rendering-a-form-from-another-controller-in-ruby-on-rails-4

  def index
    @restaurants = Restaurant.all  
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    #set the reservation as instance variable to be available for the show index in restaurant. 
    @reservation = Reservation.new 
    @reservations = Reservation.all  
  end

  # GET /restaurants/new
  #added the current_user in the new and create method as it the restaurant belongs to the user 
  # --- we wanted to make the current_user id to associated with the restaurant. 
  def new
    @restaurant = current_user.restaurants.build
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = current_user.restaurants.build(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :image)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, html: { multipart: true } do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.text_field :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<div id='restaurants' class='column'>
  <div class='content-block-list'>
    <% @restaurants.each do |restaurant| %>
      <div class='content-block-list-row'>
        <div class='column medium-7'>
            
            <%= image_tag restaurant.image.thumb %>  
            <%= restaurant.name %>
            <%= restaurant.address %>
            <%= link_to 'Show', restaurant_path(restaurant) %>

            <% if user_signed_in?  %>
            <%= link_to 'Edit', edit_restaurant_path(restaurant) %>
            <%= link_to 'Destroy',restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' } %>

            <% end %>

         </div> 
        </div>

      </div>
    <% end %>
  </div>  
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @restaurant.image.thumb %>
</p>

<!-- followed the following "http://stackoverflow.com/questions/25126741/rails-4-rendering-new-action-on-view-that-uses-different-controller" which talks about reservation variable not being initiated  -->
<%= render "/reservations/form", :reservation => @reservation %>

<% if current_user %>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <%= reservation.email %>
        <%= reservation.date_time %>
        <td><%= link_to 'Mark as Confirmed', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      </br>
    <% end %>
   </tbody>
 <% end %>

</br>
<div class="container">
</br>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
  <%= link_to 'Back', restaurants_path %>

</div>