config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'restaurants#index'

  #roots "pages#home"
  resources :restaurants do 
    resources :reservations, only: [:create]
  end

  resources :reserves 
  resources :reservations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Reservester</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      
      <li><%= link_to "Make a Reservation", new_reservation_path %></li>
      

      <% if user_signed_in? %>
        <li><%= link_to 'New Restaurant', new_restaurant_path %></li>
        <li><%= link_to 'Account Setting', edit_user_registration_path %></li> 
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %> </li>
      <% else %>
        <li><%= link_to 'Sign up', new_user_registration_path %></li> 
        <li><%= link_to "Log In", new_user_session_path %></li>
      <% end %>  
      
    
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservester</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
    <%= yield %>
  </body>
</html>